### ISSUE TITLE
Const ArcSwapOption doesn't update values

### ISSUE THREAD

**Issue by Bauxitedev** [vorner/arc-swap#75]
Hello, I am writing a program that uses a global `ArcSwapOption<String>`, but it seems the values I put into it aren't updated.

I call `store` to put something into it, but calling `load` afterwards still returns `None`.

A quick reproduction example: (you can run it directly with [`cargo script`](https://github.com/DanielKeep/cargo-script))
```rust
// cargo-deps: arc-swap="=1.5.0"
extern crate arc_swap;

use arc_swap::*;
use std::sync::Arc;

pub const SWAP: ArcSwapOption<String> = ArcSwapOption::const_empty();

fn main() {
    SWAP.store(Some(Arc::new("test".to_owned())));
    std::thread::sleep_ms(1000);
    dbg!(SWAP.load());
    dbg!(SWAP.load_full());
}
```

The program outputs...
```
[arc_swap_test.rs:12] SWAP.load() = None
[arc_swap_test.rs:13] SWAP.load_full() = None
```

...even though I clearly put the string `test` into the `ArcSwapOption`.

Am I doing something wrong here? Or is this a bug?

**Comment by vorner** [comment]
This is actually a weirdness of how `const` works, `const` is a compile time „bit pattern“ that can be copied any time it is used _even though the type is not Copy_. I'm not sure if I can prevent this trap from inside the crate in some way, I _think_ (I'm not looking for it right now) it's even mentioned in the documentation somewhere to watch out for it.

Anyway, the solution is to use `static SWAP: ...` instead of `const SWAP: ...`

**Comment by Bauxitedev** [comment]
Ah I see, `static` fixed it. Thanks for the quick response.
